postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: blueorigin
    POSTGRES_PASSWORD: max
  ports:
    - '5432:5432'
  volumes:
    - blueorigin-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - blueorigin-redis:/var/lib/redis/data

blueorigin:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/blueorigin
  ports:
    - '8000:8000'
  env_file:
    - .blueorigin.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/blueorigin
  env_file:
    - .blueorigin.env